load("//rules:docker_push.bzl", "docker_push")

docker_push(
    name = "docker_push",
    executable = True,
    registry = "docker.io",
    repository = "simonfong6/build-container",
    tag = "2",
)
