name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: l.gcr.io/google/bazel:latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: src
        run: bazel build //main:hello-world

      - name: Test
        working-directory: src
        run: bazel-bin/main/hello-world

  test:
    runs-on: ubuntu-latest
    container: l.gcr.io/google/bazel:latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        working-directory: src
        run: bazel test --test_output=all //test:hello_test
