name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: simonfong6/build-container:1

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: src
        run: bazel build //main:hello_world

      - name: Test
        working-directory: src
        run: bazel-bin/main/hello_world

  test:
    runs-on: ubuntu-latest
    container: simonfong6/build-container:1

    steps:
      - uses: actions/checkout@v2

      - name: Test
        working-directory: src
        run: bazel test --test_output=all //main:hello_world_message_unittest
